<h1 style = "color:orange">Assignment of ML</h1>

<h2>Importing Necessary Libraries and Modules</h2>

In [4]:
import pandas as pd  
import numpy as np 
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [9]:
dataset = pd.read_csv("StudentPerformanceFactors.csv")

In [3]:
dataset.head()

Hours_Studied  Attendance Parental_Involvement Access_to_Resources  \
0             23          84                  Low                High   
1             19          64                  Low              Medium   
2             24          98               Medium              Medium   
3             29          89                  Low              Medium   
4             19          92               Medium              Medium   

  Extracurricular_Activities  Sleep_Hours  Previous_Scores Motivation_Level  \
0                         No            7               79              Low   
1                         No            8               56              Low   
2                        Yes            7               91           Medium   
3                        Yes            8               98           Medium   
4                        Yes            6               65           Medium   

  Internet_Access  Tutoring_Sessions Family_Income Teacher_Quality  \
0             Yes                  0           Low          Medium   
1             Yes                  2        Medium          Medium   
2             Yes                  2        Medium          Medium   
3             Yes                  1        Medium          Medium   
4             Yes                  3        Medium            High   

  School_Type Peer_Influence  Physical_Activity Learning_Disabilities  \
0      Public       Positive                  3                    No   
1      Public       Negative                  4                    No   
2      Public        Neutral                  4                    No   
3      Public       Negative                  4                    No   
4      Public        Neutral                  4                    No   

  Parental_Education_Level Distance_from_Home  Gender  Exam_Score  
0              High School               Near    Male          67  
1                  College           Moderate  Female          61  
2             Postgraduate               Near    Male          74  
3              High School           Moderate    Male          71  
4                  College               Near  Female          70

In [7]:
#Q.1 Display column names & Datatype of each column? 

dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   Hours_Studied               6607 non-null   int64 
 1   Attendance                  6607 non-null   int64 
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64 
 6   Previous_Scores             6607 non-null   int64 
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64 
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   obje

In [8]:
# Q.2 Display total no of rows & columns?  

dataset.shape

(6607, 20)

In [9]:
#Q.3 Display only the name of columns? 

dataset.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [12]:
# Q.4 Display the name of those columns  which is having object data type? 

dataset.select_dtypes(include=object).columns

Index(['Parental_Involvement', 'Access_to_Resources',
       'Extracurricular_Activities', 'Motivation_Level', 'Internet_Access',
       'Family_Income', 'Teacher_Quality', 'School_Type', 'Peer_Influence',
       'Learning_Disabilities', 'Parental_Education_Level',
       'Distance_from_Home', 'Gender'],
      dtype='object')

In [16]:
# Q.5 Display Unique value of each column?  

for column in dataset.columns: 
    print(dataset[column].unique())

[23 19 24 29 25 17 21  9 10 14 22 15 12 20 11 13 16 18 31  8 26 28  4 35
 27 33 36 43 34  1 30  7 32  6 38  5  3  2 39 37 44]
[ 84  64  98  89  92  88  78  94  80  97  83  82  68  60  70  75  99  74
  65  62  91  90  66  69  72  63  61  86  77  71  67  87  73  96 100  81
  95  79  85  76  93]
['Low' 'Medium' 'High']
['High' 'Medium' 'Low']
['No' 'Yes']
[ 7  8  6 10  9  5  4]
[ 79  56  91  98  65  89  68  50  80  71  88  87  97  72  74  70  82  58
  99  84 100  75  54  90  94  51  57  66  96  93  52  63  81  69  95  60
  92  73  77  59  62  85  78  64  76  55  86  61  53  83  67]
['Low' 'Medium' 'High']
['Yes' 'No']
[0 2 1 3 4 5 6 7 8]
['Low' 'Medium' 'High']
['Medium' 'High' 'Low' nan]
['Public' 'Private']
['Positive' 'Negative' 'Neutral']
[3 4 2 1 5 0 6]
['No' 'Yes']
['High School' 'College' 'Postgraduate' nan]
['Near' 'Moderate' 'Far' nan]
['Male' 'Female']
[ 67  61  74  71  70  66  69  72  68  65  64  60  63  62 100  76  79  73
  78  89  75  59  86  97  83  84  80  58  94  55  92  8

In [17]:
# Q.6 Diplay first 10 Unique value of a particular column?

dataset['Attendance'].unique()[:10]

array([84, 64, 98, 89, 92, 88, 78, 94, 80, 97], dtype=int64)

In [18]:
# Q.7 Check whether null value exist in a dataset? 

dataset.isnull()

Hours_Studied  Attendance  Parental_Involvement  Access_to_Resources  \
0             False       False                 False                False   
1             False       False                 False                False   
2             False       False                 False                False   
3             False       False                 False                False   
4             False       False                 False                False   
...             ...         ...                   ...                  ...   
6602          False       False                 False                False   
6603          False       False                 False                False   
6604          False       False                 False                False   
6605          False       False                 False                False   
6606          False       False                 False                False   

      Extracurricular_Activities  Sleep_Hours  Previous_Scores  \
0                          False        False            False   
1                          False        False            False   
2                          False        False            False   
3                          False        False            False   
4                          False        False            False   
...                          ...          ...              ...   
6602                       False        False            False   
6603                       False        False            False   
6604                       False        False            False   
6605                       False        False            False   
6606                       False        False            False   

      Motivation_Level  Internet_Access  Tutoring_Sessions  Family_Income  \
0                False            False              False          False   
1                False            False              False          False   
2                False            False              False          False   
3                False            False              False          False   
4                False            False              False          False   
...                ...              ...                ...            ...   
6602             False            False              False          False   
6603             False            False              False          False   
6604             False            False              False          False   
6605             False            False              False          False   
6606             False            False              False          False   

      Teacher_Quality  School_Type  Peer_Influence  Physical_Activity  \
0               False        False           False              False   
1               False        False           False              False   
2               False        False           False              False   
3               False        False           False              False   
4               False        False           False              False   
...               ...          ...             ...                ...   
6602            False        False           False              False   
6603            False        False           False              False   
6604            False        False           False              False   
6605            False        False           False              False   
6606            False        False           False              False   

      Learning_Disabilities  Parental_Education_Level  Distance_from_Home  \
0                     False                     False               False   
1                     False                     False               False   
2                     False                     False               False   
3                     False                     False               False   
4                     False                     False               False   
...         

In [19]:
# Q.8 Display counting of null values of each column?  

dataset.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [20]:
# Q.9 Display Total number of null values in a dataset?  

dataset.isnull().sum().sum()

235

In [21]:
# Q.10 Display total % of null values in a dataset?  

null = dataset.isnull().sum().sum()
tot_value = dataset.size

null_percentage = (null/tot_value)*100

In [22]:
null_percentage

0.1778416830634176

In [23]:
# Q.11 Display mean,count,std,min,max of dataset?  

dataset.describe()

Hours_Studied   Attendance  Sleep_Hours  Previous_Scores  \
count    6607.000000  6607.000000   6607.00000      6607.000000   
mean       19.975329    79.977448      7.02906        75.070985   
std         5.990594    11.547475      1.46812        14.400397   
min         1.000000    60.000000      4.00000        50.000000   
25%        16.000000    70.000000      6.00000        63.000000   
50%        20.000000    80.000000      7.00000        75.000000   
75%        24.000000    90.000000      8.00000        88.000000   
max        44.000000   100.000000     10.00000       100.000000   

       Tutoring_Sessions  Physical_Activity   Exam_Score  
count        6607.000000        6607.000000  6607.000000  
mean            1.493719           2.967610    67.235659  
std             1.230570           1.031231     3.890456  
min             0.000000           0.000000    55.000000  
25%             1.000000           2.000000    65.000000  
50%             1.000000           3.000000    67.000000  
75%             2.000000           4.000000    69.000000  
max             8.000000           6.000000   101.000000

In [24]:
# Q.12 Display First 10 unique records of Attendence?  

dataset['Attendance'].unique()[:10]

array([84, 64, 98, 89, 92, 88, 78, 94, 80, 97], dtype=int64)

In [10]:
# Q.14 Convert NaN value using SimpleImputer class  if required? 

sm = SimpleImputer(missing_values=np.nan, strategy='most_frequent')


In [11]:
dataset[['Teacher_Quality', 'Parental_Education_Level', 'Distance_from_Home']] = sm.fit_transform(dataset[['Teacher_Quality', 
                                                                                                           'Parental_Education_Level', 
                                                                                                           'Distance_from_Home']])

In [12]:
dataset.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Family_Income                 0
Teacher_Quality               0
School_Type                   0
Peer_Influence                0
Physical_Activity             0
Learning_Disabilities         0
Parental_Education_Level      0
Distance_from_Home            0
Gender                        0
Exam_Score                    0
dtype: int64

In [13]:
from sklearn.compose import ColumnTransformer

In [14]:
# Q.13 Convert categorical data using proper encoder type?  

# Define column types
ordinal_cols = [
    "Parental_Involvement", "Access_to_Resources", "Motivation_Level",
    "Family_Income", "Teacher_Quality", "Parental_Education_Level", "Distance_from_Home"]

ordinal_categories = [
    ["Low", "Medium", "High"],
    ["Low", "Medium", "High"],
    ["Low", "Medium", "High"],
    ["Low", "Medium", "High"],
    ["Low", "Medium", "High"],
    ["High School", "College", "Postgraduate"],
    ["Near", "Moderate", "Far"]]

nominal_cols = [
    "Extracurricular_Activities", "Internet_Access", "School_Type",
    "Peer_Influence", "Learning_Disabilities", "Gender"]

column_transformer = ColumnTransformer(transformers=[
    ('ord', OrdinalEncoder(categories=ordinal_categories), ordinal_cols),
    ('nom', OneHotEncoder(drop='first', sparse_output=False), nominal_cols)], remainder="passthrough")

In [15]:
# Q.15 Apply Linear Regression Algorithm  to predict Exam_Score? 

x = dataset.iloc[:, :-1]
y = dataset['Exam_Score']

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [20]:
# Transform the data
x_train_transformed = column_transformer.fit_transform(x_train)
x_test_transformed = column_transformer.transform(x_test)

In [21]:
le = LinearRegression()
le.fit(x_train_transformed, y_train)

LinearRegression()

In [23]:
le.predict(x_test_transformed)

array([64.59551032, 65.31141313, 71.50396745, ..., 66.04490811,
       63.38867701, 71.88434731])

In [24]:
le.score(x_train_transformed, y_train)*100

71.69461033801721