In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder

In [2]:
data2 = {
    'Dosa' : [8,10,12,14,16], 
    'Price' : [10,13,16,19,22]
}

df = pd.DataFrame(data2)
df

Dosa  Price
0     8     10
1    10     13
2    12     16
3    14     19
4    16     22

In [3]:
x=df[["Dosa"]]

In [4]:
y=df["Price"]

In [5]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=2)

In [6]:
xtrain

Dosa
1    10
3    14
0     8

In [7]:
xtest

Dosa
2    12
4    16

In [8]:
ytrain

1    13
3    19
0    10
Name: Price, dtype: int64

In [9]:
ytest

2    16
4    22
Name: Price, dtype: int64

In [10]:
lr= LinearRegression()

In [21]:
lr.fit(xtrain,ytrain)

LinearRegression()

In [23]:
lr.predict([[18]])

C:\Users\sukanya\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([25.])

In [26]:
pd.read_csv("C:/python_pandas/Book11.csv")

Country   Age  Salary(k)
0   FRANCE  23.0       30.0
1    JAPAN  24.0       50.0
2  GERMANY  21.0        NaN
3    INDIA   NaN       60.0
4  AUSTRIA  27.0       90.0
5    CHINA  29.0        NaN

In [28]:
data=pd.read_csv("C:/python_pandas/Book11.csv")

In [30]:
data['Age'].dtype

dtype('float64')

In [32]:
#now change the dtype float64 to int 32
data[]  

SyntaxError: invalid syntax (2750981241.py, line 2)

In [34]:
data.columns

Index(['Country', 'Age', 'Salary(k)'], dtype='object')

In [36]:
#sm = SimpleImputer(missing_values=np.nan,strategy='mean')
sm = SimpleImputer(missing_values=np.nan,strategy = 'mean')

In [38]:
data[['Age','Salary(k)']]=sm.fit_transform(data[["Age",'Salary(k)']])

In [40]:
data

Country   Age  Salary(k)
0   FRANCE  23.0       30.0
1    JAPAN  24.0       50.0
2  GERMANY  21.0       57.5
3    INDIA  24.8       60.0
4  AUSTRIA  27.0       90.0
5    CHINA  29.0       57.5

In [42]:
data['Review']=["poor","good","avg","poor","verygood","bad"]


In [44]:
data

Country   Age  Salary(k)    Review
0   FRANCE  23.0       30.0      poor
1    JAPAN  24.0       50.0      good
2  GERMANY  21.0       57.5       avg
3    INDIA  24.8       60.0      poor
4  AUSTRIA  27.0       90.0  verygood
5    CHINA  29.0       57.5       bad

In [46]:
ords = OrdinalEncoder(categories=[["bad","poor","avg","good","verygood"]],dtype=np.int64)

In [48]:
data["Review"]=ords.fit_transform(data[["Review"]])

In [50]:
data

Country   Age  Salary(k)  Review
0   FRANCE  23.0       30.0       1
1    JAPAN  24.0       50.0       3
2  GERMANY  21.0       57.5       2
3    INDIA  24.8       60.0       1
4  AUSTRIA  27.0       90.0       4
5    CHINA  29.0       57.5       0

In [52]:
#sparsh matrix 
#

In [54]:
data['Country'].unique()

array(['FRANCE', 'JAPAN', 'GERMANY', 'INDIA', 'AUSTRIA', 'CHINA'],
      dtype=object)

In [56]:
oht=OneHotEncoder(drop="first",sparse_output=False) 

In [58]:
oht.fit_transform(data[['Country']]).toarray() # now we dont need toaaray to convert it in array where above we have done sparse=false why which it will not give in sparse matrix

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [61]:
oht.fit_transform(data[['Country']])

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [310]:
#interview que
#dummyvariable trapping=auto generate hota jitne unique row utne columns.
#multicolinearity = sab ka sum equal ni hona chaiye isliye droping a single column for finding sum of columns and the sum must be unique.

In [71]:
ht={"City":["mpnagar","indrapuri","mpnagar","newmkt","newmkt",],"Price(l)":[20,14,15,16,13]}

In [73]:
ht

{'City': ['mpnagar', 'indrapuri', 'mpnagar', 'newmkt', 'newmkt'],
 'Price(l)': [20, 14, 15, 16, 13]}

In [75]:
datas=pd.DataFrame(ht)

In [77]:
datas

City  Price(l)
0    mpnagar        20
1  indrapuri        14
2    mpnagar        15
3     newmkt        16
4     newmkt        13

In [81]:
oht=OneHotEncoder(drop="first",sparse_output=False)

In [93]:
j=oht.fit_transform(datas[["City"]])

In [95]:
j

array([[1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [97]:
newdataset=np.hstack((datas,j))

In [99]:
newdataset

array([['mpnagar', 20, 1.0, 0.0],
       ['indrapuri', 14, 0.0, 0.0],
       ['mpnagar', 15, 1.0, 0.0],
       ['newmkt', 16, 0.0, 1.0],
       ['newmkt', 13, 0.0, 1.0]], dtype=object)

In [101]:
df=pd.DataFrame(newdataset,columns=["Area","Price","F1","F2"])

In [103]:
del df["Area"]

In [105]:
df

Price   F1   F2
0    20  1.0  0.0
1    14  0.0  0.0
2    15  1.0  0.0
3    16  0.0  1.0
4    13  0.0  1.0